### ISSUE TITLE
Error in transferring Startcoin- in limbo #4 ! Need tech support to release Startcoins

### ISSUE THREAD

**Issue by monicabtc888** [startcoin-project/startcoin#10]
My issues has already been posted here:  https://github.com/startcoin-project/startwallet/issues/4

Error in transferring Startcoin- in limbo #4
 Open	monicabtc888 opened this issue 2 days ago · 2 comments

The coins sent to shapeshift never arrived.---they are not on the blockchain- and noone responded to the statwallet issue post. Please have technical support return the coins to my wallet. 

monicabtc888 commented 2 days ago
I am Username: monicabtc88

I was buying Voxels with statrcoin from here: https://sale.voxelus.com/contributors

The transfer never took place and the transaction is left as Unconfirmed in my account

---with the balance not crediting back to my account.

My Account: From address: 3HaTREBehviaqyfQWxMhoYTn6mNPKVDifE
transaction ID ID: 187bcc7059e1bee7b51439b13e1eabe3724f841110aef2712f36e5243de6bfa3
To addresss: To: sNNAjSGbsUsE2jB7Kzc3mopABhtNfkDWhv

Please cancel and recredit my account to original balance of: +695.11181458 START
 @monicabtc888
  
monicabtc888 commented 2 days ago
this is from shapeshift/voxelus........... can you-the startcoin wallet...relaese the start back to my wallet please?

....ALSO, I will relay this message to the startcoin wallet.......perhaps they can do something

From: m....
To: maximo@voxelus.com
Subject: RE: Error in transferring Startcoin- in limbo
Date: Tue, 10 Nov 2015 17:45:42 +0000

I did restart the wallet....and the Startcoin has left the wallet.---is listed in UNCONFIRMED since last night and has not recredited to my account.

The issue is then, that spapeshift/vox needs to cancel/release the transaction back to my wallet.

thanks

From: maximo@voxelus.com
Date: Tue, 10 Nov 2015 14:32:08 -0300
Subject: Re: Fwd: Error in transferring Startcoin- in limbo
To: CC: martin@voxelus.com; jon@shapeshift.io

Hi mo...

We just took a look with Jon from Shapeshinft, the team handling the transactions and he replied this to us... Could you try the steps that he enumerates below?

"What this usually means is there is an issue with the customer's wallet not broadcasting to the network correctly. He will either want to try restarting his client and making sure its fully synced (at which time it will broadcast hopefully) or if he is using an online wallet he needs to contact his wallet provider.

As this is an issue on the wallet side - there is nothing we can do to help him other than offer this advice unfortunately as the coins essentially have never been sent. "

Please let us know if this helped you.

Regards!

On Tue, Nov 10, 2015 at 2:28 PM, Jon jon@shapeshift.io wrote:
Hi Martin - so i checked and this isn't appearing in our system OR on the startcoin blockchain (http://explorer.startcoin.org/).

What this usually means is there is an issue with the customer's wallet not broadcasting to the network correctly. He will either wany to try restarting his client and making sure its fully synced (at which time it will broadcast hopefully) or if he is using an online wallet he needs to contact his wallet provider.

As this is an issue on the wallet side - there is nothing we can do to help him other than offer this advice unfortunately as the coins essentially have never been sent.

Regards,

Jon

On 11/10/15 10:21 AM, Martin Repetto wrote:
Hey guys,

I am not at my computer now but this with an altcoin just came in. Can you check?

Max can you handle this?

Martin Repetto
Sent from my iPhone - typos are in order

Begin forwarded message:

From: monica b 
Date: November 10, 2015 at 2:09:12 PM GMT-3
To: "info@voxelus.com" info@voxelus.com
Subject: Error in transferring Startcoin- in limbo

I am Username: monicabtc88
I was buying Voxels with statrcoin from here: https://sale.voxelus.com/contributors
The transfer never took place and the transaction is left as Unconfirmed in my account
---with the balance not crediting back to my account.
My Account: From address: 3HaTREBehviaqyfQWxMhoYTn6mNPKVDifE
transaction ID ID: 187bcc7059e1bee7b51439b13e1eabe3724f841110aef2712f36e5243de6bfa3
To addresss: To: sNNAjSGbsUsE2jB7Kzc3mopABhtNfkDWhv
Please cancel and recredit my account to original balance of: +695.11181458 START
 @monicabtc888
  
monicabtc888 commented 2 days ago
From shapeshift....

Monica,

Here is what I got from Shapeshift...can you check with the wallet provider looks like an issue with it..

"Max - She is incorrect as it doesn't appear on the blockchain - its a wallet problem. Not sure how else to get this across to her, if its not on the blockchain we don't have access to it. Also the fact that she even says its listed as unconfirmed mean it has not gotten a confirmation on the blockchain - if it doesn't have a confirmation we have not actually got it. So there is nothing we can do on our side as it hasn't actually been sent despite it appearing to "leave" his wallet. The only thing that means it has actually moved is confirmation on the blockchain"

Let us know,

Regards

**Comment by lukem512** [comment]
Closing due to duplication on StartWallet repository.
