### ISSUE TITLE
Needs configurable blockchain storage direcory

### ISSUE THREAD

**Issue by Nickfost** [startcoin-project/startcoin#11]
startcoin needs configurable blockchain storage directory. many wallets already have this. it can't be hard.

**Comment by lukem512** [comment]
Hi @Nickfost, thank you for the suggestion. We're current re-assessing our long-term plan for StartCOIN development. We'll bear this in mind. Stay tuned for a roadmap.

**Comment by Nickfost** [comment]
it should just be part of the GUI
