### ISSUE TITLE
Need Help Compiling StartCoin With Static Boost Libraries

### ISSUE THREAD

**Issue by SteveHadow** [startcoin-project/startcoin#13]
Hello,

I am having problems compiling StartCoin. I am building startcoind on one machine with all dependencies installed and I want to run that same binary on another machine without any of those dependencies. The first issue I hit is: 
      ./startcoind: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory

I know if I installed libboost1.54 on the machine running the binary it would work. However, this server is meant to be clean - NO GCC, NO LIBBOOST, NO LIBDB4.8. Everything has to be built into the binary. Please offer me guidance on how to do this.

**Comment by lukem512** [comment]
Hi Steve,

following [these](https://github.com/bitcoin/bitcoin/issues/3781#issuecomment-36507746) steps is a good place to start. It really depends upon your toolchain and OS but compiling with the `-static` flag and ensuring the linker includes any dynamic libs/shared objects is the basic premise. You will probably also want to `strip` the executable when it's compiled the reduce the size.

**Comment by SteveHadow** [comment]
Thanks for the response @lukem512 After some trial and error I finally got it, given your resources.

make STATIC=1 -f makefile.unix startcoind USE_UPNP=

I hope this helps someone in the future.
