### ISSUE TITLE
make failure, missing file "db_cxx.h" under Kubuntu 14.04 LTS

### ISSUE THREAD

**Issue by markettwp** [startcoin-project/startcoin#5]
make
cd /home/twp/startcoin-master/src/leveldb && CC=gcc CXX=g++ make OPT="-pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -O2" libleveldb.a libmemenv.a
make[1]: Entering directory `/home/twp/startcoin-master/src/leveldb'
make[1]:`libleveldb.a' is up to date.
make[1]: `libmemenv.a' is up to date.
make[1]: Leaving directory`/home/twp/startcoin-master/src/leveldb'
cd /home/twp/startcoin-master; /bin/sh share/genbuild.sh /home/twp/startcoin-master/build/build.h
g++ -c -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -O2 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DUSE_UPNP=1 -DSTATICLIB -DUSE_IPV6=1 -DHAVE_BUILD_INFO -DLINUX -D_FILE_OFFSET_BITS=64 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -Isrc/json -Isrc/qt -Isrc/leveldb/include -Isrc/leveldb/helpers -Ibuild -Ibuild -o build/bitcoin.o src/qt/bitcoin.cpp
In file included from src/walletdb.h:8:0,
                 from src/wallet.h:19,
                 from src/init.h:8,
                 from src/qt/bitcoin.cpp:13:
src/db.h:14:20: fatal error: db_cxx.h: No such file or directory
 #include <db_cxx.h>
                    ^
compilation terminated.
make: **\* [build/bitcoin.o] Error 1

**Comment by xlp0rk0lx** [comment]
> You're missing the BerkeleyDB dependency. Please run the following command
> 
> `sudo apt-get install libdb++-dev`

In CentOS "like" system you need to:

`yum install libdb-devel.x86_64 libdb libdb-cxx.x86_64 libdb-cxx-devel.x86_64`

After that `make -f makefile.unix clean && make `
