### ISSUE TITLE
Receive Payment API?

### ISSUE THREAD

**Issue by AnonymousPublications** [startcoin-project/startcoin#9]
Is there a web API available for handling wallet generation, perhaps something similar to [this](https://blockchain.info/api/api_receive) from bitcoin?  That would sure make porting merchant apps a breeze :)

**Comment by lukem512** [comment]
Hello,

whilst there isn't this functionality available at present, it may be something that will be available in the future. You can roll your own using the Insight-API fork (https://github.com/startcoin-project/insight-api) via http://explorer.startcoin.org/ which will allow you to receive websocket notifications for new transactions and blocks received on the network, from which you can watch the number of confirmations and issue a notification to your target app.

**Comment by AnonymousPublications** [comment]
Thanks for the reply.  insight-api looks like it's jumping to have this API added.  I have quite a bit on my plate atm, but out of curiosity, would you accept a pull request if anyone who implemented 1) receipt wallet generation, 2) forwarding from the receipt wallet to the merchant's destination wallet and 3) get request callbacks to the merchant's app?

**Comment by lukem512** [comment]
Hello,

I think the most useful thing to do would be to provide an additional application layer that interfaces with insight-api or startcoind to provide this functionality. I believe that bitcore, which we have also ported, provides functionality for accessing a daemon via RPC, as well as performing the necessary key generation tasks to generate receipt addresses. It would be a great boon to the START community if this could be implemented.

Thanks
